Depend on chart.js 2.6.0
Rather than chart.js 3.1.0. This fixes error

Error: TypeError: Cannot read properties of undefined (reading 'eventHandler')
at getEventHandler (http://localhost:3000/bundle.js:313884:22)

in my setup.